### ISSUE TITLE
Create a table named users with the following structure :

### ISSUE THREAD

**Issue by Mouhcine-ESSAFI** [Mouhcine-Essafi/Mouhcine-Essafi_Suivi#3]
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL
);

**Comment by Hackermans007** [comment]
Done.

**Comment by Hackermans007** [comment]
Done.
